#include "dnd/companions.hpp"
#include "dnd/lifecycle.hpp"
#include "srd55_fixture.hpp"
#include <catch2/catch_test_macros.hpp>

using namespace dnd;
namespace companions=dnd::srd55v2;
namespace {
const ResolvedRuleset& rules(){static const auto r=srd55fixtures::rules();return r;}
void ok(const TransitionResult& r){std::string messages;for(const auto& m:r.messages)messages+=m.code+": "+m.text+"\n";INFO(messages);REQUIRE(r.valid());}
CharacterDocument finish(CharacterDocument d){auto r=srd55fixtures::finish(d,rules());INFO(r.stopped);INFO(srd55fixtures::errors(r.evaluation));REQUIRE(r.evaluation.complete());return r.document;}
CharacterDocument complete(const std::string& cls,int level){return finish(srd55fixtures::base(cls,rules(),level));}
CharacterDocument wizard(bool prepared=false){auto d=srd55fixtures::base("wizard",rules());d.choices["spellcasting"]["wizard"]["spellbook"]["1"]={"srd55:find-familiar","srd55:magic-missile","srd55:shield","srd55:mage-armor","srd55:sleep","srd55:detect-magic"};d.choices["spellcasting"]["wizard"]["preparedSpells"]={prepared?"srd55:find-familiar":"srd55:magic-missile","srd55:shield","srd55:mage-armor","srd55:sleep"};return finish(d);}
CharacterDocument chain(int level=1){auto d=complete("warlock",level);if(level==1)d.choices["features"]["warlock"]["invocations"]={"srd55:pact-of-the-chain"};else{d.choices["features"]["warlock"]["invocations"]={"srd55:pact-of-the-chain","srd55:investment-of-the-chain-master","srd55:eldritch-mind","srd55:armor-of-shadows","srd55:devils-sight"};d.choices["features"]["warlock"]["chainMovement"]="fly";}return finish(d);}
Json inputs(const std::string& form,int minutes,const std::string& type="Fey"){Json j={{"form",form},{"minutes",minutes},{"completed",true},{"interrupted",false}};if(!type.empty())j["type"]=type;return j;}
std::string action(const CharacterDocument& d,const std::string& suffix){auto e=evaluate(d,rules());const std::string start="srd55.companions.cast."+suffix;for(const auto& a:e.actions)if(a.id.starts_with(start)&&a.available)return a.id;INFO(srd55fixtures::errors(e));FAIL("No available companion casting action for "<<suffix);return {};}
int capacity(const Evaluation& e,const std::string& id){for(const auto& r:e.resources)if(r.id==id)return r.maximum;FAIL("Missing resource "<<id);return 0;}
long long funds(const CharacterDocument& d){if(d.resources.contains("currencyCp"))return d.resources.at("currencyCp").get<long long>();const auto e=evaluate(d,rules());const auto* money=e.find("money.remainingCp");REQUIRE(money);return money->effective.get<long long>();}
Json profile(const CharacterDocument& d){const auto e=evaluate(d,rules());INFO(srd55fixtures::errors(e));REQUIRE(e.complete());const auto* c=e.find("companions.familiar");REQUIRE(c);REQUIRE(c->effective.is_array());REQUIRE(c->effective.size()==1);return c->effective[0];}
int forms(const CharacterDocument& d){int count=0;if(d.resources.contains("familiars"))for(const auto& r:d.resources["familiars"])if(r.is_object()&&r.contains("form")&&r["form"].is_string()&&!r["form"].get<std::string>().empty())++count;return count;}
CharacterDocument longRest(CharacterDocument d){auto r=executeCommand(d,rules(),{"srd55.resources.long-rest",{{"hours",8},{"sleepHours",6},{"hoursSincePrevious",24},{"interruptions",0},{"unfinished",false}}});ok(r);return r.document;}
}
TEST_CASE("A Wizard spellbook ritual pays incense and does not spend a spell slot", "[srd55-v2][companions]"){
    auto d=wizard(false);const auto e=evaluate(d,rules());const auto before=funds(d);const auto slots=capacity(e,"spellSlots.1");REQUIRE(std::find(d.choices["spellcasting"]["wizard"]["preparedSpells"].begin(),d.choices["spellcasting"]["wizard"]["preparedSpells"].end(),Json("srd55:find-familiar"))==d.choices["spellcasting"]["wizard"]["preparedSpells"].end());
    auto r=executeCommand(d,rules(),{action(d,"wizard-book-ritual"),inputs("srd55:creature-owl",70)});ok(r);CHECK(funds(r.document)==before-1000);CHECK_FALSE(r.document.resources.contains("spellSlots.1"));CHECK(capacity(evaluate(r.document,rules()),"spellSlots.1")==slots);CHECK(profile(r.document)["owner"]=="wizard");CHECK(profile(r.document)["type"]=="Fey");CHECK(r.document.resources["familiars"]["wizard"]["castingMinutes"]==70);
    const auto saved=toJson(r.document);CHECK(toJson(evaluate(documentFromJson(saved),rules()))==toJson(evaluate(r.document,rules())));CHECK(toJson(r.document)==saved);
}
TEST_CASE("Prepared casting uses the selected slot and rejects insufficient time or funds atomically", "[srd55-v2][companions]"){
    auto d=wizard(true);auto input=inputs("srd55:creature-cat",60,"Celestial");input["slotResource"]="spellSlots.1";const auto id=action(d,"slot-");const auto before=toJson(d);const auto balance=funds(d);const int slots=capacity(evaluate(d,rules()),"spellSlots.1");
    input["minutes"]=59;auto failed=executeCommand(d,rules(),{id,input});CHECK_FALSE(failed.valid());CHECK(toJson(failed.document)==before);
    input["minutes"]=60;input["interrupted"]=true;failed=executeCommand(d,rules(),{id,input});CHECK_FALSE(failed.valid());CHECK(toJson(failed.document)==before);
    input["interrupted"]=false;auto r=executeCommand(d,rules(),{id,input});ok(r);CHECK(r.document.resources["spellSlots.1"]==slots-1);CHECK(funds(r.document)==balance-1000);CHECK(profile(r.document)["type"]=="Celestial");
    d.resources["currencyCp"]=999;failed=executeCommand(d,rules(),{id,input});CHECK_FALSE(failed.valid());CHECK(funds(failed.document)==999);CHECK(forms(failed.document)==0);
}
TEST_CASE("Pact of the Chain shortens casting but does not waive consumed incense", "[srd55-v2][companions]"){
    auto d=chain();const auto balance=funds(d);const auto pact=capacity(evaluate(d,rules()),"pactMagic.slots");auto r=executeCommand(d,rules(),{"srd55.companions.cast.pact-chain",inputs("srd55:creature-imp",0,"Fiend")});ok(r);CHECK(funds(r.document)==balance-1000);CHECK_FALSE(r.document.resources.contains("pactMagic.slots"));CHECK(capacity(evaluate(r.document,rules()),"pactMagic.slots")==pact);CHECK(profile(r.document)["normalAttackAllowed"]==false);CHECK(profile(r.document)["reactionAttackByForgoingOwnerAttack"]==true);
    auto ordinary=wizard();auto illegal=executeCommand(ordinary,rules(),{"srd55.companions.cast.wizard-book-ritual",inputs("srd55:creature-imp",70)});CHECK_FALSE(illegal.valid());CHECK(forms(illegal.document)==0);
}
TEST_CASE("Wild Companion spends Wild Shape or a slot without material cost and expires on Long Rest", "[srd55-v2][companions]"){
    auto d=complete("druid",2);d.resources["currencyCp"]=0;const auto maximum=capacity(evaluate(d,rules()),"druid:wild-shape");auto r=executeCommand(d,rules(),{"srd55.companions.cast.wild-companion-shape",inputs("srd55:creature-bat",0,"")});ok(r);CHECK(funds(r.document)==0);CHECK(r.document.resources["druid:wild-shape"]==maximum-1);CHECK(profile(r.document)["type"]=="Fey");CHECK(profile(r.document)["expiry"]=="owner-long-rest");
    auto rested=longRest(r.document);CHECK(forms(rested)==0);CHECK(rested.resources["familiars"]["druid"]["status"]=="expired");
    auto slot=inputs("srd55:creature-rat",0,"");slot["slotResource"]="spellSlots.1";const int slots=capacity(evaluate(rested,rules()),"spellSlots.1");r=executeCommand(rested,rules(),{"srd55.companions.cast.wild-companion-slot",slot});ok(r);CHECK(r.document.resources["spellSlots.1"]==slots-1);CHECK(r.document.resources["druid:wild-shape"]==maximum);CHECK(funds(r.document)==0);
}
TEST_CASE("Magic Initiate uses its own free-casting resource and still permits a prepared ritual", "[srd55-v2][companions]"){
    auto d=srd55fixtures::base("fighter",rules());d.choices["backgroundId"]="srd55:sage";d.choices["backgroundBoosts"]={{"intelligence",2},{"constitution",1}};d.choices["magicInitiate"]["background"]={{"ability","wisdom"},{"cantrips",{"srd55:light","srd55:mage-hand"}},{"spell","srd55:find-familiar"}};d=finish(d);
    const auto e=evaluate(d,rules());std::string resource;for(const auto& p:e.moduleData["castingProfiles"])if(p.value("spellId","")=="srd55:find-familiar"&&p.value("freeUses",0)>0)resource=p.value("resourceId","");REQUIRE_FALSE(resource.empty());const auto balance=funds(d);const auto freeAction=action(d,"free-");auto r=executeCommand(d,rules(),{freeAction,inputs("srd55:creature-owl",60)});ok(r);CHECK(r.document.resources[resource]==0);CHECK(funds(r.document)==balance-1000);CHECK(r.document.resources["familiars"]["spell"]["castingAbility"]=="wisdom");
    CHECK_FALSE(executeCommand(r.document,rules(),{freeAction,inputs("srd55:creature-cat",60)}).valid());const auto ritual=action(r.document,"ritual-");auto again=executeCommand(r.document,rules(),{ritual,inputs("srd55:creature-cat",70)});ok(again);CHECK(again.document.resources[resource]==0);CHECK(funds(again.document)==balance-2000);
}
TEST_CASE("Recasting across Druid and Warlock sources retains one familiar identity", "[srd55-v2][companions]"){
    auto d=srd55fixtures::base("druid",rules(),2);d.choices["level"]=3;d.choices["multiclass"]=true;d.choices["advancement"]["2"]["classId"]="srd55:druid";d.choices["advancement"]["3"]["classId"]="srd55:warlock";d.choices["features"]["warlock"]["invocations"]={"srd55:pact-of-the-chain"};d=finish(d);
    auto first=executeCommand(d,rules(),{"srd55.companions.cast.wild-companion-shape",inputs("srd55:creature-cat",0,"")});ok(first);const auto identity=first.document.resources["familiars"]["druid"]["familiarId"];
    auto second=executeCommand(first.document,rules(),{"srd55.companions.cast.pact-chain",inputs("srd55:creature-imp",0,"Fiend")});ok(second);CHECK(forms(second.document)==1);CHECK(second.document.resources["familiars"]["druid"]["form"]=="");CHECK(second.document.resources["familiars"]["warlock"]["familiarId"]==identity);CHECK(profile(second.document)["owner"]=="warlock");CHECK(forms(longRest(second.document))==1);
    auto legacy=d;legacy.resources["familiars"]["druid"]={{"form","srd55:creature-cat"},{"type","Fey"}};legacy.resources["familiars"]["warlock"]={{"form","srd55:creature-imp"},{"type","Fiend"}};auto bad=evaluate(legacy,rules());CHECK_FALSE(bad.complete());CHECK(std::any_of(bad.messages.begin(),bad.messages.end(),[](const auto& m){return m.code=="srd55.companions.multiple";}));auto repaired=executeCommand(legacy,rules(),{"srd55.companions.cast.pact-chain",inputs("srd55:creature-imp",0)});ok(repaired);CHECK(forms(repaired.document)==1);
}
TEST_CASE("Dismissal preserves HP and vanished familiars require another casting", "[srd55-v2][companions]"){
    auto d=wizard();auto cast=executeCommand(d,rules(),{"srd55.companions.cast.wizard-book-ritual",inputs("srd55:creature-owl",70)});ok(cast);d=cast.document;d.resources["familiars"]["wizard"]["familiarId"]="persistent-spirit";auto dismissed=executeCommand(d,rules(),{"srd55.companions.dismiss",Json::object()});ok(dismissed);CHECK(profile(dismissed.document)["status"]=="dismissed");auto returned=executeCommand(dismissed.document,rules(),{"srd55.companions.return",{{"distanceFeet",30}}});ok(returned);CHECK(profile(returned.document)["status"]=="active");CHECK(returned.document.resources["familiars"]["wizard"]["hp"]==d.resources["familiars"]["wizard"]["hp"]);
    auto vanished=executeCommand(returned.document,rules(),{"srd55.companions.damage",{{"amount",999}}});ok(vanished);CHECK(forms(vanished.document)==0);CHECK_FALSE(executeCommand(vanished.document,rules(),{"srd55.companions.return",{{"distanceFeet",1}}}).valid());auto recast=executeCommand(vanished.document,rules(),{"srd55.companions.cast.wizard-book-ritual",inputs("srd55:creature-cat",70)});ok(recast);CHECK(recast.document.resources["familiars"]["wizard"]["familiarId"]=="persistent-spirit");
}
TEST_CASE("Chain Investment follows effective Warlock DC and a completed casting opens its history choice", "[srd55-v2][companions]"){
    auto d=chain(5);Json declarations;for(int i=0;i<5;++i)declarations["invocationLevels"][std::to_string(i)]=5;auto accepted=executeCommand(d,rules(),{"srd55.history.accept-baseline",declarations});ok(accepted);d=accepted.document;
    const auto movement="srd55.history.replace._features_warlock_chainMovement";CHECK_FALSE(executeCommand(d,rules(),{movement,{{"value","swim"}}}).valid());auto cast=executeCommand(d,rules(),{"srd55.companions.cast.pact-chain",inputs("srd55:creature-imp",0)});ok(cast);auto change=executeCommand(cast.document,rules(),{movement,{{"value","swim"}}});ok(change);d=change.document;CHECK(profile(d)["speed"]["swim"]==40);CHECK(companions::validateSrd55History(d,rules()).empty());
    d.overrides={{{"target","warlock.spellDc"},{"value",23},{"reason","Campaign familiar DC test"}}};const auto e=evaluate(d,rules());REQUIRE(e.complete());const auto* p=e.find("companions.familiar");REQUIRE(p);CHECK(p->effective[0]["featureSaveDC"]==23);CHECK(p->normal[0]["featureSaveDC"]!=23);
}
TEST_CASE("Current casting restrictions and future book entries do not create a free familiar", "[srd55-v2][companions]"){
    auto d=wizard();d.choices["purchases"]={"srd55:leather-armor"};d.choices["armorId"]="srd55:leather-armor";auto armored=evaluate(d,rules());REQUIRE(armored.complete());REQUIRE(std::any_of(armored.messages.begin(),armored.messages.end(),[](const auto& m){return m.code.ends_with("armor.untrained");}));REQUIRE(funds(d)>=1000);
    auto blocked=executeCommand(d,rules(),{"srd55.companions.cast.wizard-book-ritual",inputs("srd55:creature-cat",70)});CHECK_FALSE(blocked.valid());CHECK(forms(blocked.document)==0);
    auto future=wizard();future.choices["spellcasting"]["wizard"]["spellbook"]["1"][0]="srd55:burning-hands";future.choices["spellcasting"]["wizard"]["spellbook"]["9"]={"srd55:find-familiar"};auto e=evaluate(future,rules());CHECK(std::none_of(e.actions.begin(),e.actions.end(),[](const auto& a){return a.available&&a.id=="srd55.companions.cast.wizard-book-ritual";}));
    auto unconscious=wizard();unconscious.resources["effects"]["unconscious"]=true;CHECK_FALSE(executeCommand(unconscious,rules(),{"srd55.companions.cast.wizard-book-ritual",inputs("srd55:creature-cat",70)}).valid());
}
